version: '3.8'

services:
  mcp_server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8080:8080"
    volumes:
      - ./mcp_server:/app/mcp_server
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - db
    environment:
      - DB_USER=mg
      - DB_PASSWORD=mgpassword
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=analytics
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mg
      - POSTGRES_PASSWORD=mgpassword
      - POSTGRES_DB=analytics
    volumes:      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mg-data.local
      - PGADMIN_DEFAULT_PASSWORD=mgadmin
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

  airflow:
    image: apache/airflow:2.8.0
    command: standalone
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_data:/opt/airflow
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
  airflow_data:
